# Plugin configuration file
# Format: name,path,enabled,type,config_path
#python_plugin,../core/src/drivers/modbus_slave.py,1,0,./modbus_slave_config.ini
#python_plugin,../core/src/drivers/simple_modbus.py,1,0,./modbus_slave_config.ini
#python_plugin,../core/src/drivers/simple_modbus_sync.py,1,0,./modbus_slave_config.ini
python_plugin,../core/src/drivers/example_python_plugin.py,1,0,./modbus_slave_config.ini