# Plugin configuration file
# Format: name,path,enabled,type,config_path
modbus_slave,./core/src/drivers/plugins/python/modbus_slave_plugin/simple_modbus.py,1,0,./core/src/drivers/plugins/python/modbus_slave_plugin/modbus_slave_config.json
# example_plugin,./core/src/drivers/examples/example_python_plugin.py,1,0,./example_plugin_config.ini

